Repository apache/arrow-rs, pull requests merged in 2021-06, with the labels that each got.

#381 Respect max rowgroup size in Arrow writer
  parquet/src/arrow/arrow_writer.rs
  parquet/src/arrow/levels.rs
  parquet/src/file/properties.rs
Labels: parquet

#401 Cherry pick allow `SliceableCursor` to be constructed from an `Arc` directly to active_release
  parquet/src/util/cursor.rs
Labels: release-cherry-pick

#412 Cherry pick Add doctest for ArrayBuilder to active_release
  arrow/src/array/builder.rs
Labels: release-cherry-pick

#410 Cherry pick Add (simd) modulus op to active_release
  arrow/src/compute/kernels/arithmetic.rs
  arrow/src/datatypes/numeric.rs
Labels: release-cherry-pick

#408 Cherry pick parquet: Speed up `BitReader`/`DeltaBitPackDecoder` to active_release
  parquet/src/encodings/decoding.rs
  parquet/src/util/bit_util.rs
Labels: release-cherry-pick

#407 Cherry pick allow to read non-standard CSV to active_release
  arrow/src/csv/reader.rs
Labels: release-cherry-pick

#404 Cherry pick ensure null-counts are written for all-null columns to active_release
  parquet/src/arrow/arrow_writer.rs
  parquet/src/column/writer.rs
Labels: release-cherry-pick

#403 Cherry pick Doctests for FixedSizeBinaryArray to active_release
  arrow/src/array/array_binary.rs
Labels: release-cherry-pick

#402 Cherry pick Simplify shift kernel using new_null_array to active_release
  arrow/src/compute/kernels/window.rs
Labels: release-cherry-pick

#409 Add labels to cherry pick scripts + writeup
  dev/release/README.md
  dev/release/cherry-pick-pr.py
Labels: development-process

#418 Fix bug with null buffer offset in boolean not kernel
  arrow/src/compute/kernels/boolean.rs
Labels: arrow, bug

#429 Cherry pick add more tests for window::shift and handle boundary cases to active_release
  arrow/src/compute/kernels/window.rs
Labels: release-cherry-pick

#430 Cherry pick Respect max rowgroup size in Arrow writer to active_release
  parquet/src/arrow/arrow_writer.rs
  parquet/src/arrow/levels.rs
  parquet/src/file/properties.rs
Labels: release-cherry-pick

#431 Cherry pick Add set_bit to BooleanBufferBuilder to allow mutating bit in index to active_release
  arrow/src/array/builder.rs
  arrow/src/util/bit_util.rs
Labels: release-cherry-pick

#432 Cherry pick Fix out of bounds read in bit chunk iterator to active_release
  arrow/benches/boolean_kernels.rs
  arrow/src/util/bit_chunk_iterator.rs
Labels: release-cherry-pick

#411 Cherry pick Reduce memory usage of concat (large)utf8 to active_release
  arrow/src/array/mod.rs
  arrow/src/array/transform/mod.rs
  arrow/src/compute/kernels/concat.rs
Labels: release-cherry-pick

#434 Cherry pick Fix bug with null buffer offset in boolean not kernel to active_release
  arrow/src/compute/kernels/boolean.rs
Labels: release-cherry-pick

#433 Cherry pick Derive Eq and PartialEq for SortOptions to active_release
  arrow/src/compute/kernels/sort.rs
Labels: release-cherry-pick

#442 Cherry pick refactor lexico sort for future code reuse to active_release
  arrow/src/compute/kernels/sort.rs
Labels: release-cherry-pick

#419 Remove DictionaryArray::keys_array method
  arrow/src/array/array_dictionary.rs
  arrow/src/array/builder.rs
  arrow/src/array/ord.rs
  arrow/src/compute/kernels/cast.rs
  arrow/src/compute/kernels/sort.rs
  arrow/src/compute/kernels/take.rs
  arrow/src/util/display.rs
Labels: api-change, arrow

#451 Implement the Iterator trait for the json Reader.
  arrow/src/json/reader.rs
Labels: arrow

#438 use iterator for partition kernel instead of generating vec
  arrow/benches/partition_kernels.rs
  arrow/src/compute/kernels/partition.rs
Labels: api-change

#475 Backport clippy fixes to active release
  README.md
  arrow/src/array/array_binary.rs
  arrow/src/array/array_boolean.rs
  arrow/src/array/array_dictionary.rs
  arrow/src/array/array_primitive.rs
  arrow/src/array/array_struct.rs
  arrow/src/array/array_union.rs
  arrow/src/array/builder.rs
  arrow/src/array/equal/mod.rs
  arrow/src/array/null.rs
  arrow/src/array/ord.rs
  arrow/src/bitmap.rs
  arrow/src/compute/kernels/arithmetic.rs
  arrow/src/compute/kernels/cast.rs
  arrow/src/compute/kernels/comparison.rs
  arrow/src/compute/kernels/filter.rs
  arrow/src/compute/kernels/limit.rs
  arrow/src/compute/kernels/sort.rs
  arrow/src/compute/kernels/temporal.rs
  arrow/src/csv/reader.rs
  arrow/src/datatypes/mod.rs
  arrow/src/ffi.rs
  arrow/src/ipc/reader.rs
  arrow/src/json/reader.rs
  arrow/src/tensor.rs
  arrow/src/util/bit_util.rs
  parquet/src/arrow/array_reader.rs
  parquet/src/encodings/decoding.rs
  parquet/src/file/properties.rs
  parquet/src/file/serialized_reader.rs
  parquet/src/record/api.rs
  parquet/src/util/bit_util.rs
  parquet/src/util/memory.rs
Labels: release-cherry-pick

#465 Cherry Pick: Add Decimal to CsvWriter and improve debug display (#406)
  arrow/src/array/array_binary.rs
  arrow/src/csv/writer.rs
  arrow/src/util/display.rs
Labels: release-cherry-pick

#464 Cherry pick window::shift to work for all array types to active_release
  arrow/src/compute/kernels/window.rs
Labels: release-cherry-pick

#453 Add C data interface for decimal128 and timestamp
  .github/workflows/rust.yml
  arrow-pyarrow-integration-testing/tests/test_sql.py
  arrow/src/ffi.rs
Labels: arrow

#483 Cherry pick remove unnecessary wraps in sort to active_release
  arrow/src/compute/kernels/sort.rs
Labels: release-cherry-pick

#474 Doctest for GenericListArray.
  arrow/src/array/array_list.rs
Labels: arrow

#485 Cherry pick remove clippy unnecessary wraps suppresions in cast kernel to active_release
  arrow/src/compute/kernels/cast.rs
Labels: release-cherry-pick

#486 Cherry pick Implement the Iterator trait for the json Reader. to active_release
  arrow/src/json/reader.rs
Labels: release-cherry-pick

#487 Cherry pick remove stale comment on `ArrayData` equality and update unit tests to active_release
  arrow/src/array/array_struct.rs
  arrow/src/array/builder.rs
Labels: release-cherry-pick

#492 concatenating single element array shortcut
  arrow/src/compute/kernels/concat.rs
Labels: arrow

#493 implement second/minute helpers for temporal
  arrow/src/compute/kernels/temporal.rs
Labels: arrow

#494 Cherry pick Use partition for bool sort to active_release
  arrow/src/compute/kernels/sort.rs
Labels: release-cherry-pick

#495 Cherry pick Add C data interface for decimal128 and timestamp to active_release
  .github/workflows/rust.yml
  arrow-pyarrow-integration-testing/tests/test_sql.py
  arrow/src/ffi.rs
Labels: release-cherry-pick

#496 Cherry pick Doctest for GenericListArray. to active_release
  arrow/src/array/array_list.rs
Labels: release-cherry-pick

#497 Cherry pick special case concatenating single element array shortcut to active_release
  arrow/src/compute/kernels/concat.rs
Labels: release-cherry-pick

#499 Bump flatbuffers
  arrow/Cargo.toml
  arrow/src/ipc/gen/Message.rs
  arrow/src/ipc/gen/Schema.rs
  arrow/src/ipc/gen/SparseTensor.rs
Labels: arrow

#498 Cherry pick implement second/minute helpers for temporal to active_release
  arrow/src/compute/kernels/temporal.rs
Labels: release-cherry-pick

#490 Implement function slice for RecordBatch
  arrow/src/record_batch.rs
Labels: arrow

#505 Correct array memory usage calculation for dictionary arrays
  arrow/src/array/array.rs
  arrow/src/array/array_binary.rs
  arrow/src/array/array_boolean.rs
  arrow/src/array/array_dictionary.rs
  arrow/src/array/array_list.rs
  arrow/src/array/array_primitive.rs
  arrow/src/array/array_string.rs
  arrow/src/array/array_struct.rs
  arrow/src/array/array_union.rs
  arrow/src/array/data.rs
  arrow/src/array/null.rs
Labels: arrow

#509 Fix for primitive and boolean take kernel for nullable indices with an offset
  arrow/src/compute/kernels/take.rs
Labels: arrow

#513 Fix parquet benchmark schema
  parquet/benches/arrow_array_reader.rs
Labels: parquet
